[profile.default]
src = 'contracts'
out = 'forge-artifacts'
libs = ['node_modules', 'lib']
test = 'test'
via_ir = true
cache_path  = 'forge-cache'
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts'
]
bytecode_hash = 'none'
build_info_path = 'forge-artifacts/build-info'
ffi = true
fs_permissions = [
  { access='read-write', path='./deployments' },
  { access='read', path='./scripts/forge/deploy-config/' },
  { access='read', path='./broadcast/' },
  { access='read', path = './forge-artifacts/' }
]