[profile.default]
src = 'contracts/L2'
out = 'forge-artifacts'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'forge-cache'
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts'
]